// <auto-generated />
using JiraClone.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JiraClone.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("JiraClone.db.dbmodels.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreationTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTimestamp = 0L,
                            Email = "admin@test.com",
                            Login = "admin",
                            Name = "Jan",
                            Password = "admin",
                            Surname = "Kowalski"
                        });
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.AccountProject", b =>
                {
                    b.Property<int>("IdAccount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProject")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAccount", "IdProject");

                    b.HasIndex("IdProject");

                    b.ToTable("AccountProjects", (string)null);
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreationTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAccount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTicket")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdAccount");

                    b.HasIndex("IdTicket");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreationTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProject")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdProject");

                    b.ToTable("Statuses", (string)null);
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreationTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAsignee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProject")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdReporter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdAsignee");

                    b.HasIndex("IdProject");

                    b.HasIndex("IdReporter");

                    b.HasIndex("IdStatus");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.AccountProject", b =>
                {
                    b.HasOne("JiraClone.db.dbmodels.Account", "Account")
                        .WithMany("AccountProjects")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JiraClone.db.dbmodels.Project", "Project")
                        .WithMany("AccountProjects")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Comment", b =>
                {
                    b.HasOne("JiraClone.db.dbmodels.Account", "Account")
                        .WithMany("Comments")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JiraClone.db.dbmodels.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Status", b =>
                {
                    b.HasOne("JiraClone.db.dbmodels.Project", "Project")
                        .WithMany("Statuses")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Ticket", b =>
                {
                    b.HasOne("JiraClone.db.dbmodels.Account", "Asignee")
                        .WithMany("AsigneeTickets")
                        .HasForeignKey("IdAsignee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JiraClone.db.dbmodels.Project", "Project")
                        .WithMany("Tickets")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JiraClone.db.dbmodels.Account", "Reporter")
                        .WithMany("ReporterTickets")
                        .HasForeignKey("IdReporter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JiraClone.db.dbmodels.Status", "Status")
                        .WithMany("Tickets")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignee");

                    b.Navigation("Project");

                    b.Navigation("Reporter");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Account", b =>
                {
                    b.Navigation("AccountProjects");

                    b.Navigation("AsigneeTickets");

                    b.Navigation("Comments");

                    b.Navigation("ReporterTickets");
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Project", b =>
                {
                    b.Navigation("AccountProjects");

                    b.Navigation("Statuses");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Status", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("JiraClone.db.dbmodels.Ticket", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
